
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LUCKY
 */
public class frmMain extends javax.swing.JFrame {
String nol_jam ="";
String nol_menit="";
String nol_detik="";
    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        setJam();
        setTanggal();
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNis = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfKelas = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        tfTempat = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Tanggal = new com.toedter.calendar.JDateChooser();
        tfEmail = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        LabelJam = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LabelTanggal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbData = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btSave1 = new javax.swing.JButton();
        btDel1 = new javax.swing.JButton();
        btClear1 = new javax.swing.JButton();
        btRe1 = new javax.swing.JButton();
        btEdit1 = new javax.swing.JButton();
        btPrint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 570));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("FORM BIODATA SISWA SMK TELKOM");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("BIODATA SISWA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("NIS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        getContentPane().add(tfNis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 120, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Nama");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, 30));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Alamat");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        buttonGroup1.add(rbLaki);
        rbLaki.setText("Laki-Laki");
        jPanel1.add(rbLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setText("Perempuan");
        jPanel1.add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Jenis Kelamin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Kelas");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(tfKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 160, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane1.setViewportView(taAlamat);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 60));
        jPanel1.add(tfTempat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 160, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Tanggal Lahir");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Tempat Lahir");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));
        jPanel1.add(Tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 160, 30));
        jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 160, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 270, 490));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJam.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LabelJam.setForeground(new java.awt.Color(255, 255, 255));
        LabelJam.setText("Jam");
        jPanel2.add(LabelJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("The Real Informatic School");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        LabelTanggal.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        LabelTanggal.setForeground(new java.awt.Color(255, 255, 255));
        LabelTanggal.setText("Tanggal");
        jPanel2.add(LabelTanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 70));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbData.setBackground(new java.awt.Color(255, 204, 255));
        tbData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama", "Tempat Lahir", "Tgl Lahir", "JenisKelamin", "Kelas", "Email", "Alamat"
            }
        ));
        tbData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbData);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 720, 450));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 740, 470));

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 30));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btSave1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSave1.setText("Save");
        btSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSave1ActionPerformed(evt);
            }
        });
        jPanel5.add(btSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 30));

        btDel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btDel1.setText("Delete");
        btDel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDel1ActionPerformed(evt);
            }
        });
        jPanel5.add(btDel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 110, 30));

        btClear1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btClear1.setText("Clear");
        btClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClear1ActionPerformed(evt);
            }
        });
        jPanel5.add(btClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 110, 30));

        btRe1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btRe1.setText("Refresh");
        btRe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRe1ActionPerformed(evt);
            }
        });
        jPanel5.add(btRe1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 110, 30));

        btEdit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btEdit1.setText("Edit");
        btEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEdit1ActionPerformed(evt);
            }
        });
        jPanel5.add(btEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 110, 30));

        btPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btPrint.setText("Print");
        btPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrintActionPerformed(evt);
            }
        });
        jPanel5.add(btPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 10, 110, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 740, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTanggal()
    {
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        LabelTanggal.setText(kal.format(skrg));
    }
    
    public void setJam()
    {
        ActionListener taskPerformer = new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                
                if (nilai_jam <= 9)
                {
                    nol_jam = "0";
                }
                if (nilai_menit <= 9)
                {
                    nol_menit = "0";
                }
                if (nilai_detik <= 9)
                {
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                LabelJam.setText("Jam "+jam +":"+ menit + ":"+ detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
    
    private void btDel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDel1ActionPerformed
        int baris =  tbData.getSelectedRow();
        if (baris != -1)
        {
            String NIS = tbData.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_siswa WHERE NIS='"+NIS+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btDel1ActionPerformed

    private void btClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClear1ActionPerformed
        tfNama.setText("");
        tfTempat.setText("");
        tfNis.setText("");
        tfKelas.setText("");
        buttonGroup1.clearSelection();
        tfEmail.setText("");
        taAlamat.setText("");
        Tanggal.setDate(java.sql.Date.valueOf("2017-01-01"));
        tfTempat.setText("");
    }//GEN-LAST:event_btClear1ActionPerformed

    private void btRe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRe1ActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btRe1ActionPerformed

    private void btEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEdit1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        String JK = "";
        if (rbLaki.isSelected())
        {
            JK = "L";   
        }
        if (rbPerempuan.isSelected())
        {
            JK = "P";
        }
        
        if(tfNis.getText().equals("") || tfNama.getText().equals("") || tanggal.equals("") || JK.equals("") || 
                tfKelas.getText().equals("") || tfEmail.getText().equals("") || tfTempat.getText().equals("") || 
                taAlamat.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            String SQL = "UPDATE t_siswa SET" +"WHERE NIS='"+tfNis.getText()
            + "WHERE NamaSiswa='"+tfNama.getText()+"',"+ "WHERE JenisKelamin='"+JK+"',"   
            + "WHERE Kelas='"+tfKelas.getText()+"',"+ "WHERE Email='"+tfEmail.getText()+"'"
            + "WHERE Alamat='"+taAlamat.getText()+"'"
            +"'"
            + "WHERE TempatLahir='"+tfTempat.getText()+"'"
            + "WHERE TanggalLahir='"+tanggal+"',";
            
            int status = KoneksiDB.execute(SQL);
            if(status == 0)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }else
            {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Error", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btEdit1ActionPerformed

    private void btSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSave1ActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormat.format(Tanggal.getDate());
        String JK = "";
        if (rbLaki.isSelected())
        {
            JK = "L";   
        }
        if (rbPerempuan.isSelected())
        {
            JK = "P";
        }
        
        if(tfNis.getText().equals("") || tfNama.getText().equals("") || tanggal.equals("") || JK.equals("") || 
                tfKelas.getText().equals("") || tfEmail.getText().equals("") || tfTempat.getText().equals("") || 
                taAlamat.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else
        {
           String SQL = "INSERT INTO t_siswa VALUES('"+tfNis.getText()+"','"+tfNama.getText()+"','"+tfTempat.getText()
                   +"','"+tanggal+"','"+JK+"','"+tfKelas.getText()+"','"+tfEmail.getText()+"','"+taAlamat.getText()+"')";
            int status = KoneksiDB.execute(SQL);
        
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else
            {
            JOptionPane.showMessageDialog(this, "Data Gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
           
        }
    }//GEN-LAST:event_btSave1ActionPerformed

    private void tbDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDataMouseClicked
        // TODO add your handling code here:
        int baris = tbData.getSelectedRow();
        if(baris != -1)
        {
            tfNis.setText(tbData.getValueAt(baris, 0).toString());
            tfNama.setText(tbData.getValueAt(baris, 1).toString());
            tfTempat.setText(tbData.getValueAt(baris, 2).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try 
            {
                dateFormat = date.parse(tbData.getValueAt(baris, 3).toString());
            }
            catch (ParseException ex)
            {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            Tanggal.setDate(dateFormat);
            String JK = tbData.getValueAt(baris, 4).toString();
            if (JK.equals("Laki-Laki"))
                rbLaki.setSelected(true);
            else
                rbPerempuan.setSelected(true);
            tfKelas.setText(tbData.getValueAt(baris, 5).toString());
            tfEmail.setText(tbData.getValueAt(baris, 6).toString());
            taAlamat.setText(tbData.getValueAt(baris, 7).toString());
        }
    }//GEN-LAST:event_tbDataMouseClicked

    private void btPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrintActionPerformed
        MessageFormat header = new MessageFormat("Biodata Siswa SMK Telkom Malang");
        MessageFormat footer = new MessageFormat("Page {0,number,integer} ");
        try
        {
            tbData.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e)
        {
            System.err.format("Cannot print %a%n", e.getMessage());
        }
    }//GEN-LAST:event_btPrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJam;
    private javax.swing.JLabel LabelTanggal;
    private com.toedter.calendar.JDateChooser Tanggal;
    private javax.swing.JButton btClear1;
    private javax.swing.JButton btDel1;
    private javax.swing.JButton btEdit1;
    private javax.swing.JButton btPrint;
    private javax.swing.JButton btRe1;
    private javax.swing.JButton btSave1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tbData;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfKelas;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNis;
    private javax.swing.JTextField tfTempat;
    // End of variables declaration//GEN-END:variables

    public void selectData() 
    {
        String kolom[] = {"NIS","NamaSiswa","TempatLahir","TanggalLahir","JenisKelamin","Kelas","Email","Alamat"};
        DefaultTableModel dtm = new DefaultTableModel(null,kolom);
        String SQL = "SELECT * FROM `t_siswa`";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try
        {
            while (rs.next())
            {
                
                String NIS = rs.getString(1);
                String NamaSiswa = rs.getString(2);
                String TempatLahir = rs.getString(3);
                String TanggalLahir = rs.getString(4);
                String JenisKelamin = "";
                if ("L".equals(rs.getString(5)))
                {
                    JenisKelamin = "Laki-Laki";
                }
                else
                {
                    JenisKelamin = "Perempuan";
                }
                String Kelas = rs.getString(6);
                String Email = rs.getString(7);
                String Alamat = rs.getString(8);
                String data[] = {NIS,NamaSiswa,TempatLahir,TanggalLahir,JenisKelamin,Kelas,Email,Alamat};
                dtm.addRow(data);
                        
            }
        }
        catch (SQLException ex)
        {
            Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
            
        }
        tbData.setModel(dtm);
    }
}
